title: CocquetJulien
logo: /assets/photo_me.jpg
email: julien.cocquet@ens-lyon.fr
description: I am a M2 maths student, interested in computer science (especially in using maths in graph theory).
favicon: true
color-scheme: auto

      

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: About me
    link: ./index.html
    sublist:
      - name: Research Interests
        link: ./index.html#research-interests
      - name: Research Woorks
        link: ./index.html#research-works
      - name: Teachings
        link: ./index.html#teachings
      - name: Conference and Seminars
        link: ./index.html#conference-and-seminars
      - name: Talks
        link: ./index.html#talks
      - name: Hobbies
        link: ./index.html#hobbies
#   - name: Another Page
#     link: ./another-page.html
